name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3
      - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: wrapper
      - run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then 
            echo "Gradle wrapper files have not been updated."
            echo "Please run Gradle wrapper task and commit wrapper changes."
            exit 1
          fi
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        java-version: 11
        distribution: zulu
    - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
      with:
        arguments: build --parallel --continue
