name: Build
on: [push, pull_request]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96
      - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
        with:
          arguments: wrapper
      - run: |
          git status --porcelain
          if [[ -n $(git status --porcelain) ]]; then 
            echo "Gradle wrapper files have not been updated."
            echo "Please run Gradle wrapper task and commit wrapper changes."
            exit 1
          fi
  gradle:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
      with:
        java-version: 11
        distribution: zulu
    - uses: eskatos/gradle-command-action@ac2d340dc04d9e1113182899e983b5400c17cda1
      with:
        arguments: build --parallel --continue
